import { resolveActiveTextProvider, callTextProvider, findTextProvider } from './aiProviders';

export interface MultiLingualText {
  en: string;
  es: string;
  fr: string;
  zh: string;
  ja: string;
  ko: string;
}

const TARGET_LANGUAGES: Array<[key: 'es' | 'fr' | 'zh' | 'ja' | 'ko', name: string]> = [
  ['es', 'Spanish'],
  ['fr', 'French'],
  ['zh', 'Chinese'],
  ['ja', 'Japanese'],
  ['ko', 'Korean'],
];

/**
 * 2026-07-23 (per Reza): title/caption text produced ANYWHERE in the admin
 * dashboard -- whether AI-generated by the Media Pipeline or typed by hand
 * by the admin (at approve time, or later when editing an already-published
 * track) -- must be auto-translated into all 5 other languages immediately,
 * every time the English text is set or changed, forever.
 *
 * Root cause this fixes: THREE separate call sites (pipeline.ts's
 * /approve/:jobId for both title and a manually-overridden narrative, and
 * tracks.ts's PUT /:id for post-publish edits) were each building
 * {en: theText, es: '', fr: '', zh: '', ja: '', ko: ''} directly -- i.e.
 * storing genuinely EMPTY strings for the other 5 languages instead of
 * ever calling a translator. The frontend's locale-resolution then fell
 * back to the English string when it hit that empty value, which is why
 * the English text visibly appeared on every non-English page.
 *
 * This mirrors pipeline.ts's generateNarrative() (same provider-resolution
 * + Pollinations-fallback pattern, so callers stay consistent with
 * whatever AI provider the admin has active in Gatekeeper Hub) but does
 * NOT regenerate/rephrase the English -- it's passed through verbatim,
 * since by the time this runs the final English wording has already been
 * decided (by the admin or by the pipeline's own generation step).
 */
// 2026-07-23 (per Reza): a real occurrence was found in production --
// Korean title stored as "네온 무_sock" for "Neon Monsoon" -- a
// genuinely malformed AI response (mixed-script garbage with a stray
// underscore) that got saved verbatim because nothing ever validated
// the model's output before writing it to the database. This is a
// systemic gap, not a one-off: ANY translation call, from ANY caller,
// through ANY provider, can occasionally return junk. isPlausible()
// below is a cheap, low-false-positive check for the clearest signs of
// a broken response; isValidTranslation() below wraps it with the
// obvious "is it even non-empty" check. Never allowlists based on the
// content itself (no per-language guessing) -- it only rejects patterns
// that are essentially never present in legitimate natural-language
// prose in ANY of the 5 target languages.
function isPlausibleTranslation(text: string, englishSource: string): boolean {
  const trimmed = text.trim();
  if (!trimmed) return false;
  // Underscores are not natural punctuation in prose in any of these
  // languages -- their presence is a strong, specific signal of a
  // corrupted/truncated model response, exactly like the Neon Monsoon case.
  if (trimmed.includes('_')) return false;
  // A translation that's byte-for-byte identical to the English source
  // (for target languages that don't share a script with English) is
  // almost certainly a failed/echoed response rather than a real
  // translation.
  if (trimmed === englishSource.trim()) return false;
  return true;
}

export async function translateToAllLocales(englishText: string): Promise<MultiLingualText> {
  const blank: MultiLingualText = { en: englishText, es: '', fr: '', zh: '', ja: '', ko: '' };
  if (!englishText || !englishText.trim()) return blank;

  const translateOne = async (
    provider: Parameters<typeof callTextProvider>[0],
    model: string,
    apiKey: string,
    langName: string
  ): Promise<string> => {
    const prompt = `Translate the following into ${langName}. Reply with ONLY the translation, no extra text.`;
    // Try up to 2 times total: the model occasionally returns a garbled
    // or truncated response on the first attempt (as happened for
    // Korean above) -- a second attempt with the identical prompt is
    // enough to self-heal the vast majority of these without adding
    // meaningfully to latency/cost.
    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        const result = await callTextProvider(provider, model, apiKey, prompt, englishText);
        if (isPlausibleTranslation(result, englishText)) return result;
        console.warn(`[LocaleCascade] Implausible ${langName} translation (attempt ${attempt + 1}):`, result);
      } catch (err) {
        console.warn(`[LocaleCascade] ${langName} translation attempt ${attempt + 1} failed:`, err);
      }
    }
    // Both attempts failed validation -- leave blank rather than store
    // garbage; the frontend's own locale-resolution already falls back
    // to English when a locale value is empty.
    return '';
  };

  const runWith = async (
    provider: Parameters<typeof callTextProvider>[0],
    model: string,
    apiKey: string
  ): Promise<MultiLingualText> => {
    const translations = await Promise.allSettled(
      TARGET_LANGUAGES.map(([, langName]) => translateOne(provider, model, apiKey, langName))
    );
    const result: MultiLingualText = { ...blank };
    TARGET_LANGUAGES.forEach(([code], i) => {
      const t = translations[i];
      result[code] = t.status === 'fulfilled' ? t.value : '';
    });
    return result;
  };

  const resolved = await resolveActiveTextProvider();
  if (!('error' in resolved)) {
    try {
      return await runWith(resolved.provider, resolved.model, resolved.apiKey);
    } catch (err) {
      console.warn('[LocaleCascade] Selected text provider failed, trying Pollinations fallback:', err);
    }
  } else {
    console.warn('[LocaleCascade] No text provider selected, trying Pollinations fallback:', resolved.error);
  }

  // Same guarantee as generateNarrative(): never leave the other 5
  // languages blank just because Gatekeeper Hub has nothing configured --
  // fall back to the free, keyless Pollinations provider before giving up.
  try {
    const pollinationsText = findTextProvider('pollinations-text');
    if (!pollinationsText) throw new Error('Pollinations text fallback provider not found in registry.');
    const result = await runWith(pollinationsText, 'default', '');
    console.log('[LocaleCascade] Pollinations fallback succeeded.');
    return result;
  } catch (err) {
    console.warn('[LocaleCascade] Translation failed (both selected provider and fallback):', err);
    return blank;
  }
}

/**
 * Helper for route handlers: given whatever the client sent for a
 * title/narrative field (a plain string, a full {en,...} object, or
 * undefined if the field wasn't touched) plus the English value that was
 * already stored for this record (if any), decides whether a fresh cascade
 * translation is needed and returns the resulting MultiLingualText -- or
 * undefined if the field wasn't provided at all (so callers can leave the
 * existing DB value untouched).
 *
 * Only re-translates when the English text actually changed, so editing
 * unrelated fields (bpm, genre, etc.) never triggers pointless AI calls.
 */
export async function cascadeLocaleFieldIfChanged(
  incoming: unknown,
  previousEnglish: string | undefined
): Promise<MultiLingualText | undefined> {
  if (incoming === undefined) return undefined;

  if (typeof incoming === 'string') {
    return translateToAllLocales(incoming);
  }

  if (incoming && typeof incoming === 'object') {
    const obj = incoming as Record<string, unknown>;
    const en = typeof obj.en === 'string' ? obj.en : '';
    if (en && en !== previousEnglish) {
      return translateToAllLocales(en);
    }
    // English unchanged (or missing) -- pass through whatever was sent
    // as-is rather than silently dropping locale data the caller may
    // have deliberately included.
    return obj as unknown as MultiLingualText;
  }

  return undefined;
}
