import { resolveActiveTextProvider, callTextProvider, findTextProvider } from './aiProviders';

export interface MultiLingualText {
  en: string;
  es: string;
  fr: string;
  zh: string;
  ja: string;
  ko: string;
}

const TARGET_LANGUAGES: Array<[key: 'es' | 'fr' | 'zh' | 'ja' | 'ko', name: string]> = [
  ['es', 'Spanish'],
  ['fr', 'French'],
  ['zh', 'Chinese'],
  ['ja', 'Japanese'],
  ['ko', 'Korean'],
];

/**
 * 2026-07-23 (per Reza): title/caption text produced ANYWHERE in the admin
 * dashboard -- whether AI-generated by the Media Pipeline or typed by hand
 * by the admin (at approve time, or later when editing an already-published
 * track) -- must be auto-translated into all 5 other languages immediately,
 * every time the English text is set or changed, forever.
 *
 * Root cause this fixes: THREE separate call sites (pipeline.ts's
 * /approve/:jobId for both title and a manually-overridden narrative, and
 * tracks.ts's PUT /:id for post-publish edits) were each building
 * {en: theText, es: '', fr: '', zh: '', ja: '', ko: ''} directly -- i.e.
 * storing genuinely EMPTY strings for the other 5 languages instead of
 * ever calling a translator. The frontend's locale-resolution then fell
 * back to the English string when it hit that empty value, which is why
 * the English text visibly appeared on every non-English page.
 *
 * This mirrors pipeline.ts's generateNarrative() (same provider-resolution
 * + Pollinations-fallback pattern, so callers stay consistent with
 * whatever AI provider the admin has active in Gatekeeper Hub) but does
 * NOT regenerate/rephrase the English -- it's passed through verbatim,
 * since by the time this runs the final English wording has already been
 * decided (by the admin or by the pipeline's own generation step).
 */
export async function translateToAllLocales(englishText: string): Promise<MultiLingualText> {
  const blank: MultiLingualText = { en: englishText, es: '', fr: '', zh: '', ja: '', ko: '' };
  if (!englishText || !englishText.trim()) return blank;

  const runWith = async (
    provider: Parameters<typeof callTextProvider>[0],
    model: string,
    apiKey: string
  ): Promise<MultiLingualText> => {
    const translations = await Promise.allSettled(
      TARGET_LANGUAGES.map(([, langName]) =>
        callTextProvider(
          provider,
          model,
          apiKey,
          `Translate the following into ${langName}. Reply with ONLY the translation, no extra text.`,
          englishText
        )
      )
    );
    const result: MultiLingualText = { ...blank };
    TARGET_LANGUAGES.forEach(([code], i) => {
      const t = translations[i];
      result[code] = t.status === 'fulfilled' ? t.value : '';
    });
    return result;
  };

  const resolved = await resolveActiveTextProvider();
  if (!('error' in resolved)) {
    try {
      return await runWith(resolved.provider, resolved.model, resolved.apiKey);
    } catch (err) {
      console.warn('[LocaleCascade] Selected text provider failed, trying Pollinations fallback:', err);
    }
  } else {
    console.warn('[LocaleCascade] No text provider selected, trying Pollinations fallback:', resolved.error);
  }

  // Same guarantee as generateNarrative(): never leave the other 5
  // languages blank just because Gatekeeper Hub has nothing configured --
  // fall back to the free, keyless Pollinations provider before giving up.
  try {
    const pollinationsText = findTextProvider('pollinations-text');
    if (!pollinationsText) throw new Error('Pollinations text fallback provider not found in registry.');
    const result = await runWith(pollinationsText, 'default', '');
    console.log('[LocaleCascade] Pollinations fallback succeeded.');
    return result;
  } catch (err) {
    console.warn('[LocaleCascade] Translation failed (both selected provider and fallback):', err);
    return blank;
  }
}

/**
 * Helper for route handlers: given whatever the client sent for a
 * title/narrative field (a plain string, a full {en,...} object, or
 * undefined if the field wasn't touched) plus the English value that was
 * already stored for this record (if any), decides whether a fresh cascade
 * translation is needed and returns the resulting MultiLingualText -- or
 * undefined if the field wasn't provided at all (so callers can leave the
 * existing DB value untouched).
 *
 * Only re-translates when the English text actually changed, so editing
 * unrelated fields (bpm, genre, etc.) never triggers pointless AI calls.
 */
export async function cascadeLocaleFieldIfChanged(
  incoming: unknown,
  previousEnglish: string | undefined
): Promise<MultiLingualText | undefined> {
  if (incoming === undefined) return undefined;

  if (typeof incoming === 'string') {
    return translateToAllLocales(incoming);
  }

  if (incoming && typeof incoming === 'object') {
    const obj = incoming as Record<string, unknown>;
    const en = typeof obj.en === 'string' ? obj.en : '';
    if (en && en !== previousEnglish) {
      return translateToAllLocales(en);
    }
    // English unchanged (or missing) -- pass through whatever was sent
    // as-is rather than silently dropping locale data the caller may
    // have deliberately included.
    return obj as unknown as MultiLingualText;
  }

  return undefined;
}
